[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\bcase [0-9A-Z_a-z]+,",
    "\\bcase [0-9A-Z_a-z]+ += .+;",
    "\\bself::[0-9A-Z_a-z]+ +=> .+,",
    "\\b(Country|Currency)[:0-9A-Z_a-z]+,",
    "\\b(Country|Currency)[:0-9A-Z_a-z]+ +=> [:0-9A-Z_a-z]+,",
    "#\\[Name\\(.+\\[LanguageAlpha2::.+",
]

[default.extend-identifiers]
"Viet_Nam" = "Viet_Nam"
"Viet_Nam_Socialist_Republic_of" = "Viet_Nam_Socialist_Republic_of"
# Known typo
"Global_Mobile_Satelite_System_shared_code" = "Global_Mobile_Satelite_System_shared_code"
