<?php
declare(strict_types=1);

namespace PrinsFrank\Standards\NumberFormatting;

use PrinsFrank\Standards\Country\CountryAlpha2;
use PrinsFrank\Standards\Country\CountryAlpha3;
use PrinsFrank\Standards\Country\CountryName;
use PrinsFrank\Standards\Country\CountryNumeric;
use PrinsFrank\Standards\Language\LanguageAlpha3Bibliographic;
use PrinsFrank\Standards\Language\LanguageAlpha3Terminology;

/** Symbol used to separate the integer part from the fractional part of a number written in decimal form */
enum DecimalSeparator: string
{
    /**
     * @recommended-by BIPM
     * @recommended-by NIST
     */
    case Space = ' ';

    /**
     * @recommended-by ISO 8601 (But preference for comma in earlier version https://xml.coverpages.org/ISO-FDIS-8601.pdf)
     * @recommended-by ISO 80000-1 (or Comma)
     */
    case Dot = '.';

    /**
     * @recommended-by ISO 8601 (And preferred over the dot in earlier version https://xml.coverpages.org/ISO-FDIS-8601.pdf)
     * @recommended-by ISO 80000-1 (or Dot)
     */
    case Comma = ',';

    case Slash                    = '/';
    case Arabic_Decimal_Separator = '٫';

    public static function forCountryAndLanguage(CountryAlpha2|CountryAlpha3|CountryName|CountryNumeric $country, LanguageAlpha3Bibliographic|LanguageAlpha3Terminology $language): self
    {
        if ($country instanceof CountryAlpha2 === false) {
            $country = $country->toCountryAlpha2();
        }

        if ($language instanceof LanguageAlpha3Terminology === false) {
            $language = $language->toLanguageAlpha3Terminology();
        }

        /** @var CountryAlpha2 $country */
        /** @var LanguageAlpha3Terminology $language */
        return match ([$country, $language]) {
            [CountryAlpha2::Afghanistan, LanguageAlpha3Terminology::Persian] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Afghanistan, LanguageAlpha3Terminology::Pushto_Pashto] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Algeria, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Bahrain, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Botswana, LanguageAlpha3Terminology::English] => self::Dot,
            [CountryAlpha2::Botswana, LanguageAlpha3Terminology::Tswana] => self::Dot,
            [CountryAlpha2::Burundi, LanguageAlpha3Terminology::Rundi] => self::Comma,
            [CountryAlpha2::Burundi, LanguageAlpha3Terminology::French] => self::Comma,
            [CountryAlpha2::Cameroon, LanguageAlpha3Terminology::Fulah] => self::Comma,
            [CountryAlpha2::Cameroon, LanguageAlpha3Terminology::Ewondo] => self::Comma,
            [CountryAlpha2::Cameroon, LanguageAlpha3Terminology::French] => self::Comma,
            [CountryAlpha2::Cameroon, LanguageAlpha3Terminology::English] => self::Dot,
            [CountryAlpha2::Canada, LanguageAlpha3Terminology::English] => self::Dot,
            [CountryAlpha2::Canada, LanguageAlpha3Terminology::French] => self::Comma,
            [CountryAlpha2::Chad, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Comoros, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Djibouti, LanguageAlpha3Terminology::Afar] => self::Dot,
            [CountryAlpha2::Djibouti, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Djibouti, LanguageAlpha3Terminology::Somali] => self::Dot,
            [CountryAlpha2::Ecuador, LanguageAlpha3Terminology::Spanish_Castilian] => self::Comma,
            [CountryAlpha2::Ecuador, LanguageAlpha3Terminology::Quechua] => self::Dot,
            [CountryAlpha2::Egypt, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Eritrea, LanguageAlpha3Terminology::Afar] => self::Dot,
            [CountryAlpha2::Eritrea, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Eritrea, LanguageAlpha3Terminology::Geez] => self::Dot,
            [CountryAlpha2::Eritrea, LanguageAlpha3Terminology::Tigrinya] => self::Dot,
            [CountryAlpha2::Eswatini, LanguageAlpha3Terminology::English] => self::Dot,
            [CountryAlpha2::Eswatini, LanguageAlpha3Terminology::Swati] => self::Comma,
            [CountryAlpha2::Ethiopia, LanguageAlpha3Terminology::Afar] => self::Dot,
            [CountryAlpha2::Ethiopia, LanguageAlpha3Terminology::Amharic] => self::Dot,
            [CountryAlpha2::Ethiopia, LanguageAlpha3Terminology::Oromo] => self::Dot,
            [CountryAlpha2::Ethiopia, LanguageAlpha3Terminology::Sidamo] => self::Dot,
            [CountryAlpha2::Ethiopia, LanguageAlpha3Terminology::Somali] => self::Dot,
            [CountryAlpha2::Ethiopia, LanguageAlpha3Terminology::Tigrinya] => self::Dot,
            [CountryAlpha2::Ethiopia, LanguageAlpha3Terminology::Geez] => self::Dot,
            [CountryAlpha2::Ethiopia, LanguageAlpha3Terminology::Wolaitta_Wolaytta] => self::Dot,
            [CountryAlpha2::Ghana, LanguageAlpha3Terminology::Fulah] => self::Comma,
            [CountryAlpha2::Ghana, LanguageAlpha3Terminology::English] => self::Dot,
            [CountryAlpha2::Ghana, LanguageAlpha3Terminology::Akan] => self::Dot,
            [CountryAlpha2::Ghana, LanguageAlpha3Terminology::Ewe] => self::Dot,
            [CountryAlpha2::Ghana, LanguageAlpha3Terminology::Ga] => self::Dot,
            [CountryAlpha2::Ghana, LanguageAlpha3Terminology::Hausa] => self::Dot,
            [CountryAlpha2::Holy_See, LanguageAlpha3Terminology::Italian] => self::Comma,
            [CountryAlpha2::Holy_See, LanguageAlpha3Terminology::Latin] => self::Comma,
            [CountryAlpha2::Iran, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Iran, LanguageAlpha3Terminology::Persian] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Iraq, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Israel, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Jordan, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Kuwait, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Lebanon, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Lesotho, LanguageAlpha3Terminology::English] => self::Dot,
            [CountryAlpha2::Lesotho, LanguageAlpha3Terminology::Sotho_Southern] => self::Comma,
            [CountryAlpha2::Libya, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Luxembourg, LanguageAlpha3Terminology::German] => self::Comma,
            [CountryAlpha2::Luxembourg, LanguageAlpha3Terminology::French] => self::Comma,
            [CountryAlpha2::Macao, LanguageAlpha3Terminology::Chinese] => self::Dot,
            [CountryAlpha2::Macao, LanguageAlpha3Terminology::English] => self::Dot,
            [CountryAlpha2::Macao, LanguageAlpha3Terminology::Portuguese] => self::Comma,
            [CountryAlpha2::Mali, LanguageAlpha3Terminology::Bambara] => self::Dot,
            [CountryAlpha2::Mali, LanguageAlpha3Terminology::French] => self::Comma,
            [CountryAlpha2::Mali, LanguageAlpha3Terminology::Songhai_languages] => self::Dot,
            [CountryAlpha2::Moldova, LanguageAlpha3Terminology::Romanian_Moldavian_Moldovan] => self::Comma,
            [CountryAlpha2::Moldova, LanguageAlpha3Terminology::Russian] => self::Comma,
            [CountryAlpha2::Morocco, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Namibia, LanguageAlpha3Terminology::English] => self::Dot,
            [CountryAlpha2::Namibia, LanguageAlpha3Terminology::Afrikaans] => self::Comma,
            [CountryAlpha2::North_Macedonia, LanguageAlpha3Terminology::Macedonian] => self::Comma,
            [CountryAlpha2::North_Macedonia, LanguageAlpha3Terminology::Albanian] => self::Comma,
            [CountryAlpha2::Oman, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Pakistan, LanguageAlpha3Terminology::Persian] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Qatar, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Rwanda, LanguageAlpha3Terminology::French] => self::Comma,
            [CountryAlpha2::Rwanda, LanguageAlpha3Terminology::English] => self::Dot,
            [CountryAlpha2::Rwanda, LanguageAlpha3Terminology::Kinyarwanda] => self::Comma,
            [CountryAlpha2::Saudi_Arabia, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Senegal, LanguageAlpha3Terminology::Fulah] => self::Comma,
            [CountryAlpha2::Senegal, LanguageAlpha3Terminology::French] => self::Comma,
            [CountryAlpha2::Senegal, LanguageAlpha3Terminology::Wolof] => self::Comma,
            [CountryAlpha2::Somalia, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::South_Sudan, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Sudan, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Syrian_Arab_Republic, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Tunisia, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::United_Arab_Emirates, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Western_Sahara, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            [CountryAlpha2::Yemen, LanguageAlpha3Terminology::Arabic] => self::Arabic_Decimal_Separator,
            default => self::forCountry($country),
        };
    }

    public static function forCountry(CountryAlpha2|CountryAlpha3|CountryName|CountryNumeric $country): self
    {
        if ($country instanceof CountryAlpha2 === false) {
            $country = $country->toCountryAlpha2();
        }

        /** @var CountryAlpha2 $country */
        return match ($country) {
            CountryAlpha2::Afghanistan                             => self::Comma,
            CountryAlpha2::Aland_Islands                           => self::Comma,
            CountryAlpha2::Albania                                 => self::Comma,
            CountryAlpha2::Algeria                                 => self::Comma,
            CountryAlpha2::American_Samoa                          => self::Dot,
            CountryAlpha2::Andorra                                 => self::Comma,
            CountryAlpha2::Angola                                  => self::Comma,
            CountryAlpha2::Anguilla                                => self::Dot,
            CountryAlpha2::Antarctica                              => self::Dot,
            CountryAlpha2::Antigua_and_Barbuda                     => self::Dot,
            CountryAlpha2::Argentina                               => self::Comma,
            CountryAlpha2::Armenia                                 => self::Comma,
            CountryAlpha2::Aruba                                   => self::Comma,
            CountryAlpha2::Australia                               => self::Dot,
            CountryAlpha2::Austria                                 => self::Comma,
            CountryAlpha2::Azerbaijan                              => self::Comma,
            CountryAlpha2::Bahamas                                 => self::Dot,
            CountryAlpha2::Bahrain                                 => self::Dot,
            CountryAlpha2::Bangladesh                              => self::Dot,
            CountryAlpha2::Barbados                                => self::Dot,
            CountryAlpha2::Belarus                                 => self::Comma,
            CountryAlpha2::Belgium                                 => self::Comma,
            CountryAlpha2::Belize                                  => self::Dot,
            CountryAlpha2::Benin                                   => self::Comma,
            CountryAlpha2::Bermuda                                 => self::Dot,
            CountryAlpha2::Bhutan                                  => self::Dot,
            CountryAlpha2::Bolivia                                 => self::Comma,
            CountryAlpha2::Bonaire_Sint_Eustatius_and_Saba         => self::Comma,
            CountryAlpha2::Bosnia_and_Herzegovina                  => self::Comma,
            CountryAlpha2::Botswana                                => self::Dot,
            CountryAlpha2::Bouvet_Island                           => self::Dot,
            CountryAlpha2::Brazil                                  => self::Comma,
            CountryAlpha2::British_Indian_Ocean_Territory          => self::Dot,
            CountryAlpha2::Brunei_Darussalam                       => self::Comma,
            CountryAlpha2::Bulgaria                                => self::Comma,
            CountryAlpha2::Burkina_Faso                            => self::Comma,
            CountryAlpha2::Burundi                                 => self::Comma,
            CountryAlpha2::Cabo_Verde                              => self::Comma,
            CountryAlpha2::Cambodia                                => self::Dot,
            CountryAlpha2::Cameroon                                => self::Comma,
            CountryAlpha2::Canada                                  => self::Dot,
            CountryAlpha2::Cayman_Islands                          => self::Dot,
            CountryAlpha2::Central_African_Republic                => self::Comma,
            CountryAlpha2::Chad                                    => self::Comma,
            CountryAlpha2::Chile                                   => self::Comma,
            CountryAlpha2::China                                   => self::Dot,
            CountryAlpha2::Christmas_Island                        => self::Dot,
            CountryAlpha2::Cocos_Islands                           => self::Dot,
            CountryAlpha2::Colombia                                => self::Comma,
            CountryAlpha2::Comoros                                 => self::Comma,
            CountryAlpha2::Congo                                   => self::Comma,
            CountryAlpha2::Congo_Democratic_Republic               => self::Comma,
            CountryAlpha2::Cook_Islands                            => self::Dot,
            CountryAlpha2::Costa_Rica                              => self::Comma,
            CountryAlpha2::Cote_d_Ivoire                           => self::Comma,
            CountryAlpha2::Croatia                                 => self::Comma,
            CountryAlpha2::Cuba                                    => self::Comma,
            CountryAlpha2::Curacao                                 => self::Comma,
            CountryAlpha2::Cyprus                                  => self::Comma,
            CountryAlpha2::Czechia                                 => self::Comma,
            CountryAlpha2::Denmark                                 => self::Comma,
            CountryAlpha2::Djibouti                                => self::Comma,
            CountryAlpha2::Dominica                                => self::Dot,
            CountryAlpha2::Dominican_Republic                      => self::Dot,
            CountryAlpha2::Ecuador                                 => self::Comma,
            CountryAlpha2::Egypt                                   => self::Dot,
            CountryAlpha2::El_Salvador                             => self::Dot,
            CountryAlpha2::Equatorial_Guinea                       => self::Comma,
            CountryAlpha2::Eritrea                                 => self::Dot,
            CountryAlpha2::Estonia                                 => self::Comma,
            CountryAlpha2::Eswatini                                => self::Dot,
            CountryAlpha2::Ethiopia                                => self::Dot,
            CountryAlpha2::Falkland_Islands                        => self::Dot,
            CountryAlpha2::Faroe_Islands                           => self::Comma,
            CountryAlpha2::Fiji                                    => self::Dot,
            CountryAlpha2::Finland                                 => self::Comma,
            CountryAlpha2::France                                  => self::Comma,
            CountryAlpha2::French_Guiana                           => self::Comma,
            CountryAlpha2::French_Polynesia                        => self::Comma,
            CountryAlpha2::French_Southern_Territories             => self::Comma,
            CountryAlpha2::Gabon                                   => self::Comma,
            CountryAlpha2::Gambia                                  => self::Comma,
            CountryAlpha2::Georgia                                 => self::Comma,
            CountryAlpha2::Germany                                 => self::Comma,
            CountryAlpha2::Ghana                                   => self::Dot,
            CountryAlpha2::Gibraltar                               => self::Dot,
            CountryAlpha2::Greece                                  => self::Comma,
            CountryAlpha2::Greenland                               => self::Comma,
            CountryAlpha2::Grenada                                 => self::Dot,
            CountryAlpha2::Guadeloupe                              => self::Comma,
            CountryAlpha2::Guam                                    => self::Dot,
            CountryAlpha2::Guatemala                               => self::Dot,
            CountryAlpha2::Guernsey                                => self::Dot,
            CountryAlpha2::Guinea                                  => self::Comma,
            CountryAlpha2::Guinea_Bissau                           => self::Comma,
            CountryAlpha2::Guyana                                  => self::Dot,
            CountryAlpha2::Haiti                                   => self::Comma,
            CountryAlpha2::Heard_Island_and_McDonald_Islands       => self::Dot,
            CountryAlpha2::Holy_See                                => self::Comma,
            CountryAlpha2::Honduras                                => self::Dot,
            CountryAlpha2::Hong_Kong                               => self::Dot,
            CountryAlpha2::Hungary                                 => self::Comma,
            CountryAlpha2::Iceland                                 => self::Comma,
            CountryAlpha2::India                                   => self::Dot,
            CountryAlpha2::Indonesia                               => self::Comma,
            CountryAlpha2::Iran                                    => self::Slash,
            CountryAlpha2::Iraq                                    => self::Dot,
            CountryAlpha2::Ireland                                 => self::Dot,
            CountryAlpha2::Isle_of_Man                             => self::Dot,
            CountryAlpha2::Israel                                  => self::Dot,
            CountryAlpha2::Italy                                   => self::Comma,
            CountryAlpha2::Jamaica                                 => self::Dot,
            CountryAlpha2::Japan                                   => self::Dot,
            CountryAlpha2::Jersey                                  => self::Dot,
            CountryAlpha2::Jordan                                  => self::Dot,
            CountryAlpha2::Kazakhstan                              => self::Comma,
            CountryAlpha2::Kenya                                   => self::Dot,
            CountryAlpha2::Kiribati                                => self::Dot,
            CountryAlpha2::Korea_Democratic_Peoples_Republic       => self::Dot,
            CountryAlpha2::Korea_Republic                          => self::Dot,
            CountryAlpha2::Kuwait                                  => self::Dot,
            CountryAlpha2::Kyrgyzstan                              => self::Comma,
            CountryAlpha2::Lao_Peoples_Democratic_Republic         => self::Comma,
            CountryAlpha2::Latvia                                  => self::Comma,
            CountryAlpha2::Lebanon                                 => self::Comma,
            CountryAlpha2::Lesotho                                 => self::Dot,
            CountryAlpha2::Liberia                                 => self::Dot,
            CountryAlpha2::Libya                                   => self::Dot,
            CountryAlpha2::Liechtenstein                           => self::Dot,
            CountryAlpha2::Lithuania                               => self::Comma,
            CountryAlpha2::Luxembourg                              => self::Comma,
            CountryAlpha2::Macao                                   => self::Dot,
            CountryAlpha2::Madagascar                              => self::Dot,
            CountryAlpha2::Malawi                                  => self::Dot,
            CountryAlpha2::Malaysia                                => self::Dot,
            CountryAlpha2::Maldives                                => self::Dot,
            CountryAlpha2::Mali                                    => self::Dot,
            CountryAlpha2::Malta                                   => self::Dot,
            CountryAlpha2::Marshall_Islands                        => self::Dot,
            CountryAlpha2::Martinique                              => self::Comma,
            CountryAlpha2::Mauritania                              => self::Comma,
            CountryAlpha2::Mauritius                               => self::Comma,
            CountryAlpha2::Mayotte                                 => self::Comma,
            CountryAlpha2::Mexico                                  => self::Dot,
            CountryAlpha2::Micronesia                              => self::Dot,
            CountryAlpha2::Moldova                                 => self::Comma,
            CountryAlpha2::Monaco                                  => self::Comma,
            CountryAlpha2::Mongolia                                => self::Comma,
            CountryAlpha2::Montenegro                              => self::Comma,
            CountryAlpha2::Montserrat                              => self::Dot,
            CountryAlpha2::Morocco                                 => self::Comma,
            CountryAlpha2::Mozambique                              => self::Comma,
            CountryAlpha2::Myanmar                                 => self::Dot,
            CountryAlpha2::Namibia                                 => self::Comma,
            CountryAlpha2::Nauru                                   => self::Dot,
            CountryAlpha2::Nepal                                   => self::Dot,
            CountryAlpha2::Netherlands                             => self::Comma,
            CountryAlpha2::New_Caledonia                           => self::Comma,
            CountryAlpha2::New_Zealand                             => self::Dot,
            CountryAlpha2::Nicaragua                               => self::Dot,
            CountryAlpha2::Niger                                   => self::Comma,
            CountryAlpha2::Nigeria                                 => self::Dot,
            CountryAlpha2::Niue                                    => self::Dot,
            CountryAlpha2::Norfolk_Island                          => self::Dot,
            CountryAlpha2::North_Macedonia                         => self::Comma,
            CountryAlpha2::Northern_Mariana_Islands                => self::Dot,
            CountryAlpha2::Norway                                  => self::Comma,
            CountryAlpha2::Oman                                    => self::Dot,
            CountryAlpha2::Pakistan                                => self::Dot,
            CountryAlpha2::Palau                                   => self::Dot,
            CountryAlpha2::Palestine                               => self::Dot,
            CountryAlpha2::Panama                                  => self::Dot,
            CountryAlpha2::Papua_New_Guinea                        => self::Dot,
            CountryAlpha2::Paraguay                                => self::Comma,
            CountryAlpha2::Peru                                    => self::Comma,
            CountryAlpha2::Philippines                             => self::Dot,
            CountryAlpha2::Pitcairn                                => self::Dot,
            CountryAlpha2::Poland                                  => self::Comma,
            CountryAlpha2::Portugal                                => self::Comma,
            CountryAlpha2::Puerto_Rico                             => self::Dot,
            CountryAlpha2::Qatar                                   => self::Dot,
            CountryAlpha2::Reunion                                 => self::Comma,
            CountryAlpha2::Romania                                 => self::Comma,
            CountryAlpha2::Russian_Federation                      => self::Comma,
            CountryAlpha2::Rwanda                                  => self::Comma,
            CountryAlpha2::Saint_Barthelemy                        => self::Comma,
            CountryAlpha2::Saint_Helena_Ascension_Tristan_da_Cunha => self::Dot,
            CountryAlpha2::Saint_Kitts_and_Nevis                   => self::Dot,
            CountryAlpha2::Saint_Lucia                             => self::Dot,
            CountryAlpha2::Saint_Martin_French_part                => self::Comma,
            CountryAlpha2::Saint_Pierre_and_Miquelon               => self::Comma,
            CountryAlpha2::Saint_Vincent_and_the_Grenadines        => self::Dot,
            CountryAlpha2::Samoa                                   => self::Dot,
            CountryAlpha2::San_Marino                              => self::Comma,
            CountryAlpha2::Sao_Tome_and_Principe                   => self::Comma,
            CountryAlpha2::Saudi_Arabia                            => self::Dot,
            CountryAlpha2::Senegal                                 => self::Comma,
            CountryAlpha2::Serbia                                  => self::Comma,
            CountryAlpha2::Seychelles                              => self::Comma,
            CountryAlpha2::Sierra_Leone                            => self::Comma,
            CountryAlpha2::Singapore                               => self::Dot,
            CountryAlpha2::Sint_Maarten_Dutch_part                 => self::Comma,
            CountryAlpha2::Slovakia                                => self::Comma,
            CountryAlpha2::Slovenia                                => self::Comma,
            CountryAlpha2::Solomon_Islands                         => self::Dot,
            CountryAlpha2::Somalia                                 => self::Comma,
            CountryAlpha2::South_Africa                            => self::Comma,
            CountryAlpha2::South_Georgia_South_Sandwich_Islands    => self::Dot,
            CountryAlpha2::South_Sudan                             => self::Dot,
            CountryAlpha2::Spain                                   => self::Comma,
            CountryAlpha2::Sri_Lanka                               => self::Dot,
            CountryAlpha2::Sudan                                   => self::Dot,
            CountryAlpha2::Suriname                                => self::Comma,
            CountryAlpha2::Svalbard_Jan_Mayen                      => self::Comma,
            CountryAlpha2::Sweden                                  => self::Comma,
            CountryAlpha2::Switzerland                             => self::Comma,
            CountryAlpha2::Syrian_Arab_Republic                    => self::Dot,
            CountryAlpha2::Taiwan_Province_of_China                => self::Dot,
            CountryAlpha2::Tajikistan                              => self::Comma,
            CountryAlpha2::Tanzania                                => self::Dot,
            CountryAlpha2::Thailand                                => self::Dot,
            CountryAlpha2::Timor_Leste                             => self::Comma,
            CountryAlpha2::Togo                                    => self::Comma,
            CountryAlpha2::Tokelau                                 => self::Dot,
            CountryAlpha2::Tonga                                   => self::Dot,
            CountryAlpha2::Trinidad_and_Tobago                     => self::Dot,
            CountryAlpha2::Tunisia                                 => self::Comma,
            CountryAlpha2::Turkey                                  => self::Comma,
            CountryAlpha2::Turkmenistan                            => self::Comma,
            CountryAlpha2::Turks_and_Caicos_Islands                => self::Dot,
            CountryAlpha2::Tuvalu                                  => self::Dot,
            CountryAlpha2::Uganda                                  => self::Dot,
            CountryAlpha2::Ukraine                                 => self::Comma,
            CountryAlpha2::United_Arab_Emirates                    => self::Dot,
            CountryAlpha2::United_Kingdom                          => self::Dot,
            CountryAlpha2::United_States_Outlying_Islands          => self::Dot,
            CountryAlpha2::United_States_of_America                => self::Dot,
            CountryAlpha2::Uruguay                                 => self::Comma,
            CountryAlpha2::Uzbekistan                              => self::Comma,
            CountryAlpha2::Vanuatu                                 => self::Comma,
            CountryAlpha2::Venezuela                               => self::Comma,
            CountryAlpha2::Viet_Nam                                => self::Comma,
            CountryAlpha2::Virgin_Islands_British                  => self::Dot,
            CountryAlpha2::Virgin_Islands_U_S                      => self::Dot,
            CountryAlpha2::Wallis_and_Futuna                       => self::Comma,
            CountryAlpha2::Western_Sahara                          => self::Dot,
            CountryAlpha2::Yemen                                   => self::Dot,
            CountryAlpha2::Zambia                                  => self::Dot,
            CountryAlpha2::Zimbabwe                                => self::Comma,
        };
    }
}
