name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

permissions: {}

jobs:
  quality:
    uses: prinsfrank/CI-PHP/.github/workflows/quality.yml@7f532694f9ad3b0da45333d0c140b340488ac9b1 # v1.2.0
    permissions:
      contents: read
    with:
      PHP_VERSION: '8.3'
      PHP_VERSIONS: '["8.2", "8.3", "8.4", "8.5"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
