name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'
      timezone: 'Europe/Amsterdam'

permissions: {}

jobs:
  quality:
    uses: prinsfrank/CI-PHP/.github/workflows/quality.yml@2ffb382cac15d0b5fbe6d4915e56ede31547c824 # v1.3.1
    permissions:
      contents: read
    with:
      PHP_VERSION: '8.3'
      PHP_VERSIONS: '["8.2", "8.3", "8.4", "8.5"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
