name: Daily TLD comparison

on:
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

env:
  PHP_VERSION: '8.3'

jobs:
  compare-tlds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Download TLD list from IANA
        run: "wget 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt'"

      - name: Dump TLDs from spec
        run: composer run create-tld-file

      - name: Compare
        run: "diff <(grep -v '^#' ./tlds-alpha-by-domain.txt) ./tlds.txt"
