name: Shared Spec Update

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string

env:
  PHP_VERSION: '8.3'

permissions: {}

jobs:
  update-spec:
    name: Update spec
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create pull requests
      pull-requests: write # to create pull requests
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run standard update command
        env:
          TYPE: ${{ inputs.type }}
        run: composer run update-spec-$TYPE

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE: ${{ inputs.type }}
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH="update-spec/$TYPE"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "Automatic $TYPE spec update from upstream changes"
          git push origin "$BRANCH" --force

          gh pr create \
            --title "Automatic $TYPE spec update" \
            --body "This PR makes sure the content of this package is updated with upstream changes in the specs." \
            --label "spec-update" \
            --label "automated pr" \
            --reviewer PrinsFrank \
            || echo "PR already exists or couldn't be created"
