name: Specs

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]

env:
  PHP_VERSION: '8.3'
  GH_TOKEN: ${{ github.token }}
  COMPOSER_ROOT_VERSION: dev-main # see https://getcomposer.org/doc/articles/troubleshooting.md#dependencies-on-the-root-package

jobs:
  specs-regenerate:
    name: Regenerate specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        spec:
          - "country"
          - "currency"
          - "http-methods"
          - "http-status-codes"
          - "language-extensive"
          - "language"
          - "language-subtag"
          - "scripts"
          - "tld"
          - "php-regex-script"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Update spec
        run: composer run update-spec-${{ matrix.spec }}

      - name: Check for changes
        run: git diff --exit-code
