name: Daily HTTP status update

on:
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  update-specs:
    uses: ./.github/workflows/reusable-update-spec.yml
    with:
      type: http-status-code
