name: Daily HTTP status update

on:
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

jobs:
  update-specs:
    uses: ./.github/workflows/update-spec.yml
    with:
      type: http-status-code
