name: Daily HTTP status code spec update

on:
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

jobs:
  update-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run standard update command
        run: composer update-spec -- --type=http-status-codes
      - name: Run CSFixer
        run: composer cs:fix
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automatic HTTP status code spec update from upstream changes
          delete-branch: true
          title: 'Automatic Http status code spec update'
          branch: update-spec/http-status
          body: |
            This PR makes sure the content of this package is updated with upstream changes in the specs.
          labels: |
            spec-update
            automated pr
          reviewers: prinsfrank
