name: Update standards

on:
  schedule:
    - cron: '00 19 * * *'

jobs:
  update-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run standard update command
        run: composer update-spec
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automatic spec update from upstream changes
          delete-branch: true
          title: 'Automatic spec update'
          body: |
            This PR makes sure the content of this package is updated with upstream changes in the specs.
          labels: |
            spec-update
            automated pr
          reviewers: prinsfrank
