name: Daily Language Extensive update

on:
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  update-specs:
    uses: ./.github/workflows/update-spec.yml
    with:
      type: language-extensive
