name: Daily HTTP Method update

on:
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

jobs:
  update-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install
      - name: Run standard update command
        run: composer update-spec-http-method
      - name: Run CSFixer
        run: composer cs:fix
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automatic HTTP method spec update from upstream changes
          delete-branch: true
          title: 'Automatic Http method spec update'
          branch: update-spec/http-method
          body: |
            This PR makes sure the content of this package is updated with upstream changes in the specs.
          labels: |
            spec-update
            automated pr
          reviewers: prinsfrank
